Public Interface Interface_Q
    'Sub init()
    Sub questionNO_init(ByVal iNo As Integer)
    Sub question_examinate01()
    Sub question_examinate02()
    Sub question_examinate03()
    Sub question_examinate04()
    Sub question_examinate05()
    Sub question_examinate06()
    Sub question_examinate07()
    Sub question_examinate08()
    Sub question_examinate09()
    Sub question_examinate10()
    Sub question_examinate11()
    Sub question_examinate12()
    Sub question_examinate13()
    Sub question_examinate14()
    Sub question_examinate15()
    Sub question_examinate16()
    Sub question_examinate17()
    Sub question_examinate18()
    Sub question_examinate19()
    Sub question_examinate20()

End Interface
